name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build extension for chromium
        run: npm run build:chromium

      - name: Build extension for firefox
        run: npm run build:firefox

      - name: Upload Chromium build
        uses: actions/upload-artifact@v7
        with:
          name: google-search-region-chromium
          path: googlesearch-force-region-chromium.zip

      - name: Upload Firefox build
        uses: actions/upload-artifact@v7
        with:
          name: google-search-region-firefox
          path: googlesearch-force-region-firefox.zip